/**
 * Shared ERP chrome — progressive-disclosure layout primitives.
 * Prefer these over hand-rolled .mod-header / filter strips / status pills.
 */

export { ResponsivePageContainer } from './ResponsivePageContainer'
export { ModuleChrome } from './ModuleChrome'
export { PageToolbar } from './PageToolbar'
export { PrimaryActionButton } from './PrimaryActionButton'
export { SecondaryActionMenu } from './SecondaryActionMenu'
export { StatusBadge } from './StatusBadge'
export { FormSection } from './FormSection'
export { FormField } from './FormField'
export { RecordHeader } from './RecordHeader'
export { WorkflowStageBar } from './WorkflowStageBar'
export type { WorkflowStage } from './WorkflowStageBar'
export { AsyncActionButton } from './AsyncActionButton'
export { DestructiveAction } from './DestructiveAction'
export { EmptyState } from './EmptyState'
export { Breadcrumbs } from './Breadcrumbs'
export { SmartButtons } from './SmartButtons'
export type { SmartButton, SmartButtonTone } from './SmartButtons'
export { OnboardingChecklist, useOnboardingState } from './OnboardingChecklist'
export { FilterDrawer } from './FilterDrawer'
export { OperationalSummary } from './OperationalSummary'
export { CompactInfoNotice } from './CompactInfoNotice'
export { TruncatedText } from './TruncatedText'
export { TablePageLayout } from './TablePageLayout'
export { PermissionDeniedState } from './PermissionDeniedState'
export { CalendarView } from './CalendarView'
export type { CalendarItem } from './CalendarView'
export { PivotView } from './PivotView'
