-- Read-only. Unique rules the app's schema (prisma/schema.prisma) expects,
-- and whether this database has them. A missing one makes the app's saves
-- that rely on it fail (production's stock_movements lacked
-- uq_stock_movements_blob_id, so its stock moves never reached the table).
-- Changes nothing.
--
--   cd /var/www/deed-erp
--   DB=$(grep -h '^DATABASE_URL' .env* | head -1 | sed -E 's#.*/([^/?"]+).*#\1#')
--   sudo -u postgres psql -P pager=off -d "$DB" < scripts/unique-index-check.sql

WITH expected(tbl, idx) AS (VALUES
  ('leave_policies', 'leave_policies_effective_year_key'),
  ('users', 'users_employee_id_key'),
  ('users', 'users_username_key'),
  ('users', 'users_email_key'),
  ('user_sessions', 'user_sessions_token_hash_key'),
  ('departments', 'departments_name_key'),
  ('employees', 'employees_employee_number_key'),
  ('employees', 'employees_id_number_key'),
  ('leave_requests', 'leave_requests_reference_key'),
  ('leave_balances', 'uq_leave_balance_emp_type_year'),
  ('attendance_records', 'attendance_records_employee_id_work_date_key'),
  ('payroll_runs', 'payroll_runs_run_reference_key'),
  ('salary_advances', 'salary_advances_reference_key'),
  ('clients', 'clients_client_number_key'),
  ('suppliers', 'suppliers_supplier_number_key'),
  ('brands', 'brands_name_key'),
  ('products', 'products_sku_key'),
  ('products', 'products_barcode_key'),
  ('serial_numbers', 'serial_numbers_serial_number_key'),
  ('serial_numbers', 'serial_numbers_inventory_barcode_key'),
  ('partner_api_keys', 'partner_api_keys_key_hash_key'),
  ('stock_levels', 'stock_levels_product_id_key'),
  ('bulk_stock_levels', 'uq_bulk_stock_product_location'),
  ('inventory_batches', 'idx_inventory_batches_product_batch'),
  ('stock_movements', 'uq_stock_movements_blob_id'),
  ('stock_adjustments', 'stock_adjustments_reference_key'),
  ('purchase_orders', 'purchase_orders_po_number_key'),
  ('goods_received_notes', 'goods_received_notes_grn_number_key'),
  ('supplier_payments', 'supplier_payments_idempotency_key_key'),
  ('leads', 'leads_inbound_message_id_key'),
  ('sales_inbound_emails', 'sales_inbound_emails_provider_msg_uniq'),
  ('sale_orders', 'sale_orders_order_number_key'),
  ('sale_orders', 'sale_orders_quote_id_key'),
  ('sale_orders', 'ux_sale_orders_version'),
  ('quotes', 'quotes_quote_number_key'),
  ('invoices', 'invoices_invoice_number_key'),
  ('payments', 'payments_idempotency_key_key'),
  ('mpesa_stk_requests', 'mpesa_stk_requests_merchant_request_id_key'),
  ('mpesa_stk_requests', 'mpesa_stk_requests_checkout_request_id_key'),
  ('credit_notes', 'credit_notes_credit_note_number_key'),
  ('delivery_notes', 'delivery_notes_blob_id_key'),
  ('delivery_notes', 'delivery_notes_dn_number_key'),
  ('repairs', 'repairs_job_number_key'),
  ('pos_sessions', 'pos_sessions_session_number_key'),
  ('pos_transactions', 'pos_transactions_transaction_number_key'),
  ('kilimall_listings', 'kilimall_listings_product_id_key'),
  ('kilimall_listings', 'kilimall_listings_kilimall_sku_key'),
  ('kilimall_orders', 'kilimall_orders_kilimall_order_id_key'),
  ('outbound_releases', 'outbound_releases_ref_key'),
  ('outbound_releases', 'outbound_releases_invoice_id_key'),
  ('outbound_releases', 'outbound_releases_repair_id_key'),
  ('outbound_releases', 'outbound_releases_delivery_note_id_key'),
  ('ai_documents', 'uq_ai_documents_source'),
  ('account_codes', 'account_codes_code_key'),
  ('journals', 'journals_code_key'),
  ('journal_entries', 'journal_entries_ref_key'),
  ('journal_entries', 'uq_journal_source_version'),
  ('analytic_accounts', 'analytic_accounts_code_key'),
  ('analytic_budget_lines', 'uq_analytic_budget_dimension'),
  ('product_valuations', 'product_valuations_product_id_key'),
  ('valuation_events', 'valuation_events_event_key_key'),
  ('approval_rules', 'approval_rules_approval_type_key'),
  ('deposits', 'uq_deposits_ref'),
  ('deposit_payments', 'deposit_payments_idempotency_key_key'),
  ('holdovers', 'uq_holdovers_ref'),
  ('price_lists', 'price_lists_code_key'),
  ('device_serial_costs', 'device_serial_costs_serial_id_key'),
  ('reconfiguration_work_orders', 'reconfiguration_work_orders_ref_key'),
  ('reconfiguration_work_orders', 'reconfiguration_work_orders_valuation_event_key_key'),
  ('reconfiguration_work_orders', 'reconfiguration_work_orders_completion_event_key_key'),
  ('reconfiguration_qa_checks', 'reconfiguration_qa_checks_work_order_id_check_key_key'),
  ('fiscal_periods', 'uq_fiscal_period_dates'),
  ('bank_accounts', 'uq_bank_account_name'),
  ('bank_statements', 'uq_bank_statement_ref'),
  ('bank_statement_lines', 'uq_statement_external_id'),
  ('bank_reconciliation_matches', 'uq_bank_recon_match'),
  ('expense_records', 'expense_records_reference_key'),
  ('tax_transactions', 'uq_tax_source_line'),
  ('inventory_ledger_entries', 'inventory_ledger_entries_event_key_key'),
  ('statutory_rule_versions', 'uq_statutory_rule_effective'),
  ('fixed_assets', 'fixed_assets_asset_number_key'),
  ('asset_depreciation_entries', 'uq_asset_depreciation_period'),
  ('financial_reconciliations', 'uq_fin_reconciliation_period'),
  ('notification_events', 'notification_events_idempotency_key_key'),
  ('notification_recipients', 'notification_recipients_event_id_user_id_key'),
  ('notification_outbox', 'notification_outbox_event_id_key'),
  ('notification_deliveries', 'notification_deliveries_idempotency_key_key'),
  ('notification_attempts', 'notification_attempts_delivery_id_attempt_no_key'),
  ('notification_preferences', 'notification_preferences_user_id_event_type_key'),
  ('notification_templates', 'notification_templates_event_type_channel_version_key'),
  ('notification_escalations', 'notification_escalations_event_id_level_target_user_id_key'),
  ('communication_threads', 'communication_threads_thread_key_key'),
  ('communication_messages', 'communication_messages_provider_message_key_key'),
  ('communication_messages', 'communication_messages_notification_delivery_id_key'),
  ('notification_dead_letters', 'notification_dead_letters_delivery_id_key'),
  ('report_snapshots', 'report_snapshots_scope_key_key'),
  ('background_jobs', 'background_jobs_unique_key_key'),
  ('erp_state_records', 'uq_erp_state_record_key')
)
SELECT e.tbl AS table_name, e.idx AS expected_unique_rule,
       CASE WHEN NOT EXISTS (SELECT 1 FROM pg_tables t WHERE t.schemaname = 'public' AND t.tablename = e.tbl) THEN 'table missing'
            ELSE 'MISSING' END AS state
FROM expected e
WHERE NOT EXISTS (
  SELECT 1 FROM pg_indexes i WHERE i.schemaname = 'public' AND i.indexname = e.idx
)
AND NOT EXISTS (
  SELECT 1 FROM pg_constraint c WHERE c.conname = e.idx
)
ORDER BY 3, 1;
