import type { PublicUser } from './types'

export const PUBLIC_USERS: PublicUser[] = [
  {
    id: 'u_brian',
    username: 'brian',
    name: 'Brian',
    role: 'admin',
    modules: [
      'dashboard','sales','crm','inventory','contacts','purchase','pos','repair',
      'refurbishment','delivery','ecommerce','kilimall','accounting','hr','outsource',
      'sops','after_sales','expenses','leave','my_documents',
    ],
    active: true,
    createdAt: '2026-04-25',
  },
  {
    id: 'u1',
    username: 'admin',
    name: 'System Administrator',
    role: 'admin',
    modules: ['dashboard', 'sales', 'crm', 'inventory', 'contacts', 'purchase', 'repair', 'accounting', 'hr', 'delivery'],
    active: true,
    createdAt: '2026-04-01',
  },
  {
    id: 'u2',
    username: 'finance1',
    name: 'Faith Achieng',
    role: 'finance',
    modules: ['dashboard', 'accounting', 'hr'],
    active: true,
    createdAt: '2026-04-01',
  },
  {
    id: 'u3',
    username: 'leadtech1',
    name: 'Peter Mwangi',
    role: 'lead_tech',
    modules: ['dashboard', 'repair', 'inventory', 'hr'],
    active: true,
    createdAt: '2026-04-01',
  },
  {
    id: 'u4',
    username: 'tech1',
    name: 'James Otieno',
    role: 'repair_tech',
    modules: ['dashboard', 'repair', 'hr'],
    active: true,
    createdAt: '2026-04-01',
  },
  {
    id: 'u5',
    username: 'tech2',
    name: 'Amina Hassan',
    role: 'repair_tech',
    modules: ['dashboard', 'repair', 'hr'],
    active: true,
    createdAt: '2026-04-01',
  },
  {
    id: 'u6',
    username: 'sales1',
    name: 'Grace Njeri',
    role: 'sales_rep',
    modules: ['dashboard', 'sales', 'crm', 'contacts', 'hr'],
    active: true,
    createdAt: '2026-04-01',
  },
]

